[build]
builder = "nixpacks"

[deploy]
startCommand = "python minimal_test.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
name = "becoming-one-ai"