[build]
builder = "nixpacks"

[deploy]
startCommand = "python working_bot.py"
# healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
name = "becoming-one-ai"