[build]
builder = "nixpacks"

[deploy]
startCommand = "python compass_api.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
name = "compass-api"
